### ISSUE TITLE
simplejson 3.7.3 won't install on cygwin

### ISSUE THREAD

**Issue by furlongm** [simplejson/simplejson#120]
This happens every time with 3.7.3. No issue with 3.6.5.

```
Collecting simplejson==3.7.3
  Using cached simplejson-3.7.3.tar.gz
Installing collected packages: simplejson
  Found existing installation: simplejson 3.6.5
    Uninstalling simplejson-3.6.5:
      Successfully uninstalled simplejson-3.6.5
  Running setup.py install for simplejson
      0 [main] python2.7 5044 child_info_fork::abort: unable to map C:\cygwin\lib\python2.7\site-packages\simplejson\_speedups.dll, Win32 error 126
    Error [Errno 11] Resource temporarily unavailable while executing command /usr/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-MYU23f/simplejson/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-w0K0LP-record/install-record.txt --single-version-externally-managed --compile
  Rolling back uninstall of simplejson
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 223, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 297, in run
    root=options.root_path,
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 622, in install
    **kwargs
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 857, in install
    show_stdout=False,
  File "/usr/lib/python2.7/site-packages/pip/utils/__init__.py", line 701, in call_subprocess
    cwd=cwd, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1231, in _execute_child
    self.pid = os.fork()
OSError: [Errno 11] Resource temporarily unavailable
```

**Comment by etrepum** [comment]
I think this is a problem with `pip`. Could you report this issue there? `simplejson` doesn't import itself in its `setup.py` so fixing this is really out of my control.

**Comment by etrepum** [comment]
Here's what I suspect is happening:

* pip imports simplejson
* pip uninstalls the version of simplejson its using
* pip tries to use simplejson when installing the new one, which fails because the dll it needs has been uninstalled
