### ISSUE TITLE
Unable to pip install --upgrade simplejson under cygwin

### ISSUE THREAD

**Issue by kgeo** [simplejson/simplejson#138]
I installed the latest cygwin (64bit) under Windows 10 today, which comes with simplejson 3.6.5 in its packages. I want to use the Google API Python Client. pip installing that, loads and updates a bunch of packages, but crashes when trying to upgrade simplejson. I can isolate that as follows:

```
$ pip install --upgrade simplejson
Collecting simplejson
  Using cached simplejson-3.8.2.tar.gz
Installing collected packages: simplejson
  Found existing installation: simplejson 3.6.5
    Uninstalling simplejson-3.6.5:
      Successfully uninstalled simplejson-3.6.5
      1 [main] python2.7 7452 child_info_fork::abort: unable to map C:\cygwin64\lib\python2.7\site-packages\simplejson\_speedups.dll, Win32 error 126
    Error [Errno 11] Resource temporarily unavailable while executing command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-_nSo9B/simplejson/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-yReBDw-record/install-record.txt --single-version-externally-managed --compile
  Running setup.py install for simplejson ... error
  Rolling back uninstall of simplejson
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 880, in install
    spinner=spinner,
  File "/usr/lib/python2.7/site-packages/pip/utils/__init__.py", line 678, in call_subprocess
    cwd=cwd, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1231, in _execute_child
    self.pid = os.fork()
OSError: [Errno 11] Resource temporarily unavailable
```

It might have to do with the backslashes in `C:\cygwin64\lib\python2.7\site-packages\simplejson\_speedups.dll`, but I am not sure. The fle exists and is at that particular path.

**Comment by etrepum** [comment]
This isn't really an issue that has anything to do with simplejson in particular, and isn't something that could be fixed by changing anything here. Would be good to ask this kind of question of pip.
