### ISSUE TITLE
UnicodeDecodeError despite using ensure_ascii=False 

### ISSUE THREAD

**Issue by john-savveo** [simplejson/simplejson#139]
I ran across a difference in how the standard json module and simplejson handles a specific str with "ensure_ascii=False".

With the standard json module, there is no UnicodeDecodeError.

With simplejson there is a UnicodeDecodeError.

The str in question is "\xe3", which is not a valid UTF-8 or UTF-16 string.  

Please see the example below:

```
$ python
Python 2.6.6 (r266:84292, Oct 16 2014, 16:53:15)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.51)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import json
>>> import simplejson
>>> simplejson.__version__
'3.8.2'
>>> s="\xe3"
>>> s
'\xe3'
>>> json.dumps(s,ensure_ascii=False)
'"\xe3"'
>>> simplejson.dumps(s,ensure_ascii=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jwiederhold/.pyenv/versions/arcviz_2.6/lib/python2.6/site-packages/simplejson/__init__.py", line 397, in dumps
    **kw).encode(obj)
  File "/Users/jwiederhold/.pyenv/versions/arcviz_2.6/lib/python2.6/site-packages/simplejson/encoder.py", line 271, in encode
    return encode_basestring(o)
  File "/Users/jwiederhold/.pyenv/versions/arcviz_2.6/lib/python2.6/site-packages/simplejson/encoder.py", line 51, in encode_basestring
    s = s.decode('utf-8')
  File "/Users/jwiederhold/.pyenv/versions/arcviz_2.6/lib/python2.6/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe3 in position 0: unexpected end of data
>>>
```

**Comment by etrepum** [comment]
The behavior in the json library is wrong, input that is not valid UTF-8 should not be serializable so raising a UnicodeDecodeError is the correct thing to do.
