### ISSUE TITLE
How does tests run on OS without os.fork()?

### ISSUE THREAD

**Issue by fedor4ever** [simplejson/simplejson#148]
Hi! I want run full test suite.

I modify `__init__.py` in tests folder and run tests via test_sjson.py on phone. [My fork](https://github.com/fedor4ever/simplejson)
Some test failed because Symbian doesn't support fork mechanics. How important are these tests?

After test ends I saw in python console "C Extension not aviable" 4 times. Not in log file.
I build _speedups.pyd for PyS60 2.0.0(Symbian port based on 2.5.4 CPython). I can import it.

Here test results:
........................................................................................................EEE................................................
======================================================================
ERROR: test_infile_outfile (simplejson.tests.test_tool.TestTool)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\resource\python25\simplejson\tests\test_tool.py", line 90, in test_infile_outfile
    self.runTool(args=[infile.name, outfile.name]),
  File "c:\resource\python25\simplejson\tests\test_tool.py", line 62, in runTool
    stdout=subprocess.PIPE)
  File "scriptshell_dir_043026\subprocess.py", line 594, in __init__
  File "scriptshell_dir_043026\subprocess.py", line 1017, in _execute_child
AttributeError: 'module' object has no attribute 'fork'

======================================================================
ERROR: test_infile_stdout (simplejson.tests.test_tool.TestTool)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\resource\python25\simplejson\tests\test_tool.py", line 78, in test_infile_stdout
    self.runTool(args=[infile.name]),
  File "c:\resource\python25\simplejson\tests\test_tool.py", line 62, in runTool
    stdout=subprocess.PIPE)
  File "scriptshell_dir_043026\subprocess.py", line 594, in __init__
  File "scriptshell_dir_043026\subprocess.py", line 1017, in _execute_child
AttributeError: 'module' object has no attribute 'fork'

======================================================================
ERROR: test_stdin_stdout (simplejson.tests.test_tool.TestTool)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\resource\python25\simplejson\tests\test_tool.py", line 70, in test_stdin_stdout
    self.runTool(data=self.data.encode()),
  File "c:\resource\python25\simplejson\tests\test_tool.py", line 62, in runTool
    stdout=subprocess.PIPE)
  File "scriptshell_dir_043026\subprocess.py", line 594, in __init__
  File "scriptshell_dir_043026\subprocess.py", line 1017, in _execute_child
AttributeError: 'module' object has no attribute 'fork'

======================================================================
ERROR: test_infile_outfile (simplejson.tests.test_tool.TestTool)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\resource\python25\simplejson\tests\test_tool.py", line 90, in test_infile_outfile
    self.runTool(args=[infile.name, outfile.name]),
  File "c:\resource\python25\simplejson\tests\test_tool.py", line 62, in runTool
    stdout=subprocess.PIPE)
  File "scriptshell_dir_043026\subprocess.py", line 594, in __init__
  File "scriptshell_dir_043026\subprocess.py", line 1017, in _execute_child
AttributeError: 'module' object has no attribute 'fork'

======================================================================
ERROR: test_infile_stdout (simplejson.tests.test_tool.TestTool)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\resource\python25\simplejson\tests\test_tool.py", line 78, in test_infile_stdout
    self.runTool(args=[infile.name]),
  File "c:\resource\python25\simplejson\tests\test_tool.py", line 62, in runTool
    stdout=subprocess.PIPE)
  File "scriptshell_dir_043026\subprocess.py", line 594, in __init__
  File "scriptshell_dir_043026\subprocess.py", line 1017, in _execute_child
AttributeError: 'module' object has no attribute 'fork'

======================================================================
ERROR: test_stdin_stdout (simplejson.tests.test_tool.TestTool)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\resource\python25\simplejson\tests\test_tool.py", line 70, in test_stdin_stdout
    self.runTool(data=self.data.encode()),
  File "c:\resource\python25\simplejson\tests\test_tool.py", line 62, in runTool
    stdout=subprocess.PIPE)
  File "scriptshell_dir_043026\subprocess.py", line 594, in __init__
  File "scriptshell_dir_043026\subprocess.py", line 1017, in _execute_child
AttributeError: 'module' object has no attribute 'fork'

----------------------------------------------------------------------
Ran 254 tests in 126.596s

FAILED (errors=6)

**Comment by etrepum** [comment]
The tests for the tool are not at all important for most usage. You'll never run `python -msimplejson.tool` in that kind of environment. Those tests can be safely skipped or ignored.

"C Extension not available" is probably being printed because the extension isn't where the tests are looking for it. `python setup.py test` expects the extension to be built in-place, e.g. with `python setup.py build_ext -i`.
