### ISSUE TITLE
UnicodeDecodeError when install simplejson under python 3.6.0

### ISSUE THREAD

**Issue by Ducatel** [simplejson/simplejson#182]
Hi, 
There is a UnicodeDecodeError  exception when I try to install simplejson.

## Error stack
```
(project_virtual_env) J:\....\project>pip install simplejson
Collecting simplejson
  Using cached simplejson-3.11.1.tar.gz
Installing collected packages: simplejson
  Running setup.py install for simplejson ... error
Exception:
Traceback (most recent call last):
  File "c:\users\me\appdata\local\temp\project_virtual_env\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 66: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\me\appdata\local\temp\project_virtual_env\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\me\appdata\local\temp\project_virtual_env\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\users\me\appdata\local\temp\project_virtual_env\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\users\me\appdata\local\temp\project_virtual_env\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "c:\users\me\appdata\local\temp\project_virtual_env\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "c:\users\me\appdata\local\temp\project_virtual_env\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 66: invalid continuation byte
```

## Step to reproduce
```
SET VIRTUAL_ENV_PATH=%TEMP%\project_virtual_env
J:\....\project>python.exe -m venv "%VIRTUAL_ENV_PATH%"
J:\....\project>"%VIRTUAL_ENV_PATH%\Scripts\activate.bat"  "%VIRTUAL_ENV_PATH%\pyvenv.cfg"
J:\....\project>pip install simplejson
```

## Extra info

* Python x64 3.6.0
* Pip 9.0.1
* Windows 10 x64

**Comment by etrepum** [comment]
It seems that this problem is likely to be in pip, not simplejson. Perhaps you should report it there?

**Comment by Ducatel** [comment]
So the error will be fixed in the next release of `pip` ;)
