### ISSUE TITLE
LookupError: unknown encoding: hex 

### ISSUE THREAD

**Issue by zeshinsei** [simplejson/simplejson#21]
Python 2.6.2

simplejson is no longer working (no changes were made to the server):

```
>>> import simplejson
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-i686/egg/simplejson/__init__.py", line 111, in <module>
  File "build/bdist.linux-i686/egg/simplejson/decoder.py", line 29, in <module>
  File "build/bdist.linux-i686/egg/simplejson/decoder.py", line 21, in _floatconstants
LookupError: unknown encoding: hex
```

**Comment by cesarcruz** [comment]
I got the same problem in a subset of 2.4.3, It solves by adding 

```python
from encodings import hex_codec
``` 

in file `simplejson.decoder.py`
