### ISSUE TITLE
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by Allan-Nava** [simplejson/simplejson#226]
When I add Authorization Bearer to my request, I have this error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 471, in dispatch
    self.initial(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 388, in initial
    self.perform_authentication(request)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 314, in perform_authentication
    request.user
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/request.py", line 222, in user
    self._authenticate()
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/request.py", line 375, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/usr/local/lib/python3.5/dist-packages/oidc_auth/authentication.py", line 47, in authenticate
    userinfo = self.get_userinfo(bearer_token)
  File "/usr/local/lib/python3.5/dist-packages/oidc_auth/util.py", line 40, in wrapped
    cached_value = fn(this, *args)
  File "/usr/local/lib/python3.5/dist-packages/oidc_auth/authentication.py", line 74, in get_userinfo
    response = requests.get(self.oidc_config['userinfo_endpoint'],
  File "/usr/local/lib/python3.5/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.5/dist-packages/oidc_auth/authentication.py", line 35, in oidc_config
    return requests.get(api_settings.OIDC_ENDPOINT + '/.well-known/openid-configuration', verify=default_ssl_check).json()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.5/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.5/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by serhiy-storchaka** [comment]
Unlikely the problem is in simplejson. Look at the input string. Seems it is not valid JSON.

**Comment by etrepum** [comment]
Sorry but this isn’t an issue with simplejson, it’s with one of the other libraries you’re using. This is the exception you get when you attempt to decode invalid JSON. Looks like oidc_auth (or wherever its configuration comes from) is closer to the root cause.
