### ISSUE TITLE
Test failures with Python 3.6 and 3.7 (simplejson.tests.test_tool.TestTool)

### ISSUE THREAD

**Issue by FRidh** [simplejson/simplejson#241]
```
======================================================================
FAIL: test_infile_outfile (simplejson.tests.test_tool.TestTool)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/simplejson-3.16.0/simplejson/tests/test_tool.py", line 104, in test_infile_outfile
    self.runTool(args=[infile_name, outfile_name]),
  File "/build/simplejson-3.16.0/simplejson/tests/test_tool.py", line 73, in runTool
    self.assertEqual(strip_python_stderr(err), ''.encode())
AssertionError: b"/nix/store/b888dk7a2fbs1br06h996wyifbsir[239 chars]on 3" != b''

======================================================================
FAIL: test_infile_stdout (simplejson.tests.test_tool.TestTool)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/simplejson-3.16.0/simplejson/tests/test_tool.py", line 88, in test_infile_stdout
    self.runTool(args=[infile_name]),
  File "/build/simplejson-3.16.0/simplejson/tests/test_tool.py", line 73, in runTool
    self.assertEqual(strip_python_stderr(err), ''.encode())
AssertionError: b"/nix/store/b888dk7a2fbs1br06h996wyifbsir[239 chars]on 3" != b''

======================================================================
FAIL: test_stdin_stdout (simplejson.tests.test_tool.TestTool)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/simplejson-3.16.0/simplejson/tests/test_tool.py", line 79, in test_stdin_stdout
    self.runTool(data=self.data.encode()),
  File "/build/simplejson-3.16.0/simplejson/tests/test_tool.py", line 73, in runTool
    self.assertEqual(strip_python_stderr(err), ''.encode())
AssertionError: b"/nix/store/b888dk7a2fbs1br06h996wyifbsir[239 chars]on 3" != b''

----------------------------------------------------------------------
Ran 144 tests in 2.081s
```

Full log: https://nix-cache.s3.amazonaws.com/log/6vrfcwyxvgiy0yq15xalgli7v16f603f-python3.7-simplejson-3.16.0.drv

**Comment by etrepum** [comment]
This is a Nix problem. Can you report this to the appropriate Nix repository? If a PR to workaround whatever Nix is doing is appropriate, I’d be happy to review one, but I don’t have the Nix expertise or environment to debug this myself.

**Comment by FRidh** [comment]
Turns out a `DeprecationWarning` was shown, and the test did not expect that. Because the test relies on `stderr` I suggest turning off warnings.

At our side we'll solve it for now with `PYTHONWARNINGS="ignore"`. Note I'm the Python Nixpkgs maintainer.

**Comment by etrepum** [comment]
Are any of the deprecation warnings coming from simplejson’s code, or from Nix infrastructure? AFAIK there are none in simplejson.
