### ISSUE TITLE
Cannot stop simplejson converting bytes to str

### ISSUE THREAD

**Issue by lukehinds** [simplejson/simplejson#253]
I would like to have simplejson not convert a dict from `bytes` to `str` when loading (if that is possible). 

From reading the docs I assumed `encoding=None` would achieve this, but that results in `Object of type bytes is not JSON serializable`

test code:

```
try:
    import simplejson as json
except ImportError:
    print("Not loaded!")
    exit()

my_str = b'{"foo": 42}'

print('my_str:', type(my_str))
print('my_str:', my_str)

dumped_str = json.dumps(my_str, encoding='utf-8')

print('dumped_str:', type(load_my_str))
print('dumped_str:', load_my_str)
```

```
python3 test.py 
my_str: <class 'bytes'>
my_str: b'{"foo": 42}'
dumped_str: <class 'str'>
dumped_str: "{\"foo\": 42}"
```

```
load_my_str = json.dumps(my_str)
```

```
python3 test.py 
my_str: <class 'bytes'>
my_str: b'{"foo": 42}'
dumped_str: <class 'str'>
dumped_str: "{\"foo\": 42}"
```

```
load_my_str = json.dumps(my_str, encoding=None)
```

```
my_str: <class 'bytes'>
my_str: b'{"foo": 42}'
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    dumped_str = json.dumps(my_str, encoding=None)
  File "/home/luke/.local/lib/python3.7/site-packages/simplejson/__init__.py", line 399, in dumps
    **kw).encode(obj)
  File "/home/luke/.local/lib/python3.7/site-packages/simplejson/encoder.py", line 296, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/luke/.local/lib/python3.7/site-packages/simplejson/encoder.py", line 378, in iterencode
    return _iterencode(o, 0)
  File "/home/luke/.local/lib/python3.7/site-packages/simplejson/encoder.py", line 273, in default
    o.__class__.__name__)
TypeError: Object of type bytes is not JSON serializable
```

**Comment by etrepum** [comment]
That’s not possible, JSON is defined in terms of characters and not bytes so the implementation doesn’t have a way to do that for you. Consider that the input could have an escape sequence that represents any possible character. Just doesn’t make sense as bytes.
