### ISSUE TITLE
RecursionError on pathological input

### ISSUE THREAD

**Issue by Google-Autofuzz** [simplejson/simplejson#270]
When passing the attached input to the following script, I get an unexpected RecursionError exception, while using the latest git version of simplejson.

```
import sys
import simplejson

with open(sys.argv[1], 'rb') as f:
    data = f.read()
try:
    simplejson.dumps(simplejson.loads(data))
except simplejson.errors.JSONDecodeError:
    pass
except UnicodeDecodeError:
    pass
```

```
$ python simplejson_repro.py test.txt
Traceback (most recent call last):
  File "simplejson_repro.py", line 7, in <module>
    simplejson.dumps(simplejson.loads(data))
  File "/home/user/ven/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/home/user/ven/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/home/user/ven/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
RecursionError: maximum recursion depth exceeded while decoding a JSON object from a unicode string

```

[test.txt](https://github.com/simplejson/simplejson/files/5475507/test.txt)

**Comment by serhiy-storchaka** [comment]
Try ti increse the recursion limit by `sys.setrecursionlimit()`.

**Comment by Google-Autofuzz** [comment]
This won't solve the problem, since it's always doable to generate an sufficenlty large input to hit the recursion limit.
