### ISSUE TITLE
module _speedups conflicts with markupsafe package

### ISSUE THREAD

**Issue by vorfol** [simplejson/simplejson#280]
markupsafe package already has _speedups module. his name is "markupsafe._speedups".

```
>>> import markupsafe
>>> import simplejson
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/wrk_disk/vorfolomeev/local/lib/python3.11/site-packages/simplejson/__init__.py", line 135, in <module>
    from .encoder import JSONEncoder, JSONEncoderForHTML
  File "/wrk_disk/vorfolomeev/local/lib/python3.11/site-packages/simplejson/encoder.py", line 15, in <module>
    c_encode_basestring_ascii, c_make_encoder = _import_speedups()
  File "/wrk_disk/vorfolomeev/local/lib/python3.11/site-packages/simplejson/encoder.py", line 12, in _import_speedups
    return _speedups.encode_basestring_ascii, _speedups.make_encoder
AttributeError: module 'markupsafe._speedups' has no attribute 'encode_basestring_ascii'

```
I think the m_name in moduledef in _speedups.c must be "simplejson._speedups" instead of just "_speedups".

**Comment by vorfol** [comment]
the issue is not here
