### ISSUE TITLE
decimal.Decimal serialization error in Google Cloud Run

### ISSUE THREAD

**Issue by dreinon** [simplejson/simplejson#294]
I am experiencing errors when trying to serialize decimal.Decimal properties of a dictionary in Cloud Run:
```py
Traceback (most recent call last): File "/project/app/lib/functions/recibos_desglose.py", line 10, in create_linea_desglose response = db.table("recibos_desglose").insert([linea]).execute() File "/project/__pypackages__/3.10/lib/supabase/lib/query_builder.py", line 31, in _execute_monkey_patch response = func(f"{url}?{query}", headers=self.session.headers, **additional_kwargs) File "/project/__pypackages__/3.10/lib/httpx/_api.py", line 304, in post return request( File "/project/__pypackages__/3.10/lib/httpx/_api.py", line 100, in request return client.request( File "/project/__pypackages__/3.10/lib/httpx/_client.py", line 776, in request request = self.build_request( File "/project/__pypackages__/3.10/lib/httpx/_client.py", line 346, in build_request return Request( File "/project/__pypackages__/3.10/lib/httpx/_models.py", line 1097, in __init__ headers, stream = encode_request(content, data, files, json) File "/project/__pypackages__/3.10/lib/httpx/_content.py", line 183, in encode_request return encode_json(json) File "/project/__pypackages__/3.10/lib/httpx/_content.py", line 146, in encode_json body = json_dumps(json).encode("utf-8") File "/usr/local/lib/python3.10/json/__init__.py", line 231, in dumps return _default_encoder.encode(obj) File "/usr/local/lib/python3.10/json/encoder.py", line 199, in encode chunks = self.iterencode(o, _one_shot=True) File "/usr/local/lib/python3.10/json/encoder.py", line 257, in iterencode return _iterencode(o, 0) File "/usr/local/lib/python3.10/json/encoder.py", line 179, in default raise TypeError(f'Object of type {o.__class__.__name__} ' TypeError: Object of type Decimal is not JSON serializable
```

It only happens in Cloud, in local it works fine.

**Comment by etrepum** [comment]
In case anyone else comes across this issue, that traceback does not have simplejson in it. The problem was likely that simplejson was not installed or another package was not configured appropriately.

**Comment by dreinon** [comment]
Right, I closed it because of that. I used simplejson with a library that used requests internally. Since this library switched to httpx, which doesn't allow the use of simplejson, I was running into this issue in the cloud since my local version of the library was still using requests.
Sorry about that :)
