### ISSUE TITLE
Broken support for encoding MagicMock objects

### ISSUE THREAD

**Issue by hxxpn** [simplejson/simplejson#322]
Hello, I found an issue with the `simplejson.dumps()` method in version `3.19.x`

Scenario: When I  try to encode any kind of MagicMock object I get the following error message:

`
Traceback (most recent call last):
  File "/Users/xxx/projects/min_miner/json_encoder_test.py", line 5, in <module>
    print(simplejson.dumps(example))
  File "/Users/xxx/projects/min_miner/.venv/lib/python3.9/site-packages/simplejson/__init__.py", line 378, in dumps
    return _default_encoder.encode(obj)
  File "/Users/xxx/projects/min_miner/.venv/lib/python3.9/site-packages/simplejson/encoder.py", line 298, in encode
    chunks = self.iterencode(o)
  File "/Users/xxx/projects/min_miner/.venv/lib/python3.9/site-packages/simplejson/encoder.py", line 379, in iterencode
    return _iterencode(o, 0)
TypeError: _asdict() must return a dict, not MagicMock
`

This occurs for versions of simplejson higher than `3.17.4`

Code to reproduce the issue:
```python
import simplejson
from unittest.mock import MagicMock

example = MagicMock()
print(simplejson.dumps(example))
```

**Comment by etrepum** [comment]
This is expected behavior, there's no defined encoding for MagicMock. You need to implement one either with a default method or have the MagicMock define its own encoding one way or another.

```
❯ python3
Python 3.11.7 (main, Dec  4 2023, 18:10:11) [Clang 15.0.0 (clang-1500.1.0.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import unittest.mock
>>> import simplejson
>>> mock = unittest.mock.MagicMock()
>>> simplejson.dumps(mock)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bob/src/simplejson/simplejson/__init__.py", line 378, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bob/src/simplejson/simplejson/encoder.py", line 298, in encode
    chunks = self.iterencode(o)
             ^^^^^^^^^^^^^^^^^^
  File "/Users/bob/src/simplejson/simplejson/encoder.py", line 379, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
TypeError: _asdict() must return a dict, not MagicMock
>>> mock.for_json = lambda: None
>>> simplejson.dumps(mock)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bob/src/simplejson/simplejson/__init__.py", line 378, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bob/src/simplejson/simplejson/encoder.py", line 298, in encode
    chunks = self.iterencode(o)
             ^^^^^^^^^^^^^^^^^^
  File "/Users/bob/src/simplejson/simplejson/encoder.py", line 379, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
TypeError: _asdict() must return a dict, not MagicMock
>>> simplejson.dumps(mock, for_json=True)
'null'
>>> mock._asdict = lambda: {"magic":"mock"}
>>> simplejson.dumps(mock)
'{"magic": "mock"}'
```
