### ISSUE TITLE
Decoding error when loading Infinity

### ISSUE THREAD

**Issue by gnilrets** [simplejson/simplejson#325]
With simplejson==3.18.4, this works fine:

```python
Python 3.11.9 (main, Apr 19 2024, 11:43:47) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import simplejson
>>> simplejson.loads('{"value": Infinity}')
{'value': inf}
```

However, with simplejson==3.19.2, it fails:
```python
Python 3.11.9 (main, Apr 19 2024, 11:43:47) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import simplejson
>>> simplejson.loads('{"value": Infinity}')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sterling.paramore/miniconda3/envs/wtf/lib/python3.11/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sterling.paramore/miniconda3/envs/wtf/lib/python3.11/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
               ^^^^^^^^^^^^^^^^^^
  File "/Users/sterling.paramore/miniconda3/envs/wtf/lib/python3.11/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 11 (char 10)
```

**Comment by etrepum** [comment]
This regression is intentional for JSON conformance and security reasons, you can use the allow_nan=True option 

```
>>> import simplejson
>>> simplejson.__version__
'3.19.2'
>>> simplejson.loads('{"value": Infinity}', allow_nan=True)
{'value': inf}
```

**Comment by gnilrets** [comment]
@etrepum - I discovered this issue when upgrading some packages that interacted with an API using the requests library and a different library that imported simplejson.  I don't have any control over what requests does nor do I have any control over the API (which can return Infinity), so I'm kinda stuck here.

**Comment by etrepum** [comment]
Ultimately it's the API that's broken and not returning standards compliant JSON. The allow_nan option has been available for a very long time (since 2005-12-31) and can be explicitly set in a backwards compatible way, it's really only the default that changed (about 18 years later than it should have).
